### ISSUE TITLE
`get_twitch_schedule` with default settings fails when category is empty

### ISSUE THREAD

**Issue by rpodcast** [KoderKow/twitchr#23]
While I imagine this is quite rare, I stumbled upon a case where `get_twitch_schedule` errors out for a streamer that does not have any categories returned as part of the response. Here's example output when trying to obtain the schedule for `broadcaster_id = "593801461"`:

```r
id <- "593801461"
r <- twitchr::get_schedule(broadcaster_id = id, clean_json = TRUE)                                                                
Error: Can't subset columns that don't exist.
✖ Column `category` doesn't exist.
```

When obtaining the raw output (i.e. setting `clean_json = FALSE`), we get the raw response back. But in this specific example, each schedule item in the raw json has empty slots for category. Hence the processing done below fails due to the `category` column never actually making it to the initial tidy data frame.

https://github.com/KoderKow/twitchr/blob/34e99050280663663085ea133ac9f5adeb810253/R/clean_data.R#L256-L259

Here's a snippet that shows the initial processing before it would fail:
```
id <- "593801461"
r <- twitchr::get_schedule(broadcaster_id = id, clean_json = FALSE)
response_data <- purrr::pluck(r, "data")
initial_segments <- response_data$segments %>% dplyr::bind_rows()

dplyr::glimpse(initial_segments)

Rows: 20
Columns: 5
$ id           <chr> "eyJzZWdtZW50SUQiOiJkMjE4MGQ3Yi0zN2ZlLTRlMzgtOWMyNC00…
$ start_time   <chr> "2021-08-22T20:30:00Z", "2021-08-24T01:00:00Z", "2021…
$ end_time     <chr> "2021-08-22T22:30:00Z", "2021-08-24T02:00:00Z", "2021…
$ title        <chr> "Fun and Games!", "Craf-Tea-ness", "Tea Leaves and Le…
$ is_recurring <lgl> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,…
```

**Comment by KoderKow** [comment]
Nice catch! I just pushed up some [code](https://github.com/KoderKow/twitchr/commit/8c4ec37d3725f3e7b7060eb70577d63b639deb60) to fix it :) That should have it working for you now. When you have time try the updated code and let me know if that works for you!

**Comment by rpodcast** [comment]
Works flawlessly now! Thank you for the quick fix 🙏
