### ISSUE TITLE
`clean_get_schedule` fails when segments are NULL

### ISSUE THREAD

**Issue by rpodcast** [KoderKow/twitchr#24]
This issue will have some irony as it happens when trying to get the schedule data of your [theeatgamelove](https://www.twitch.tv/theeatgamelove) account: In situations where the `segments` slot of `response_data` is actually NULL, then the `clean_get_schedule` fails at this step:

https://github.com/KoderKow/twitchr/blob/8c4ec37d3725f3e7b7060eb70577d63b639deb60/R/clean_data.R#L256-L260

In the short term I can simply wrap `twitchr::get_schedule()` inside `purrr::safely()` so I can ensure my [streamer_data](https://github.com/rpodcast/streamer_data/blob/master/streamer_data.R) pipeline continues with the rest of the twitch IDs, but it looks like there could be some additional error checking to account for this (rare) possibility.

**Comment by KoderKow** [comment]
Haha, of course it's tied to my account! The `data` element will now return `NULL` when there is no schedule, similar to the `vacation` element. I just pushed up this change, let me know if this this gets things back into working order for you!

**Comment by KoderKow** [comment]
Closing this, I am assuming this has been fixed.
