### ISSUE TITLE
twitch keyword search, get all videos and get historical chat messages

### ISSUE THREAD

**Issue by PursuitOfDataScience** [KoderKow/twitchr#26]
Hi,

We are collecting data from Twitch for some group project. The `twitchr` package works great. A few things I need your help on collecting data from Twitch.

When I use `get_videos()` for a particular user, 100 at maximum videos will return. I am wondering if there is any way to get all the videos from this very user, just like `get_all_follows()`? 

If I would like to use the package to return all videos related to a certain topic, say "vaccine" for this example, is there a way to get them?

Also, videos might contain a lot of chat messages, if possible, could you shed some light on how to collect them from certain videos? Thanks for your help. Thanks in advance!

**Comment by KoderKow** [comment]
Hey @PursuitOfDataScience!

> We are collecting data from Twitch for some group project. The twitchr package works great. A few things I need your help on collecting data from Twitch.

Apologies for the late response, I have been busy with work! I appreciate your kind words!

> When I use get_videos() for a particular user, 100 at maximum videos will return. I am wondering if there is any way to get all the videos from this very user, just like get_all_follows()?

I have just pushed up a new function; `get_all_videos()` that will operate a lot like `get_video()`. This will paginate as many times as it can until there is no response.

> Also, videos might contain a lot of chat messages, if possible, could you shed some light on how to collect them from certain videos? Thanks for your help. Thanks in advance!

Twitch currently does not have a **public** API for obtaining this information. In the next few weeks if I have time I can look into it and try to get it added for you! I will leave this issue open until then.

Thanks,

Kyle

**Comment by PursuitOfDataScience** [comment]
Thanks for shedding great light on how to use the API. It's very helpful!

**Comment by KoderKow** [comment]
@PursuitOfDataScience I added `get_video_comments()` to the package. Check it out here <https://koderkow.github.io/twitchr/reference/get_video_comments.html>

**Comment by PursuitOfDataScience** [comment]
Thanks!
